### ISSUE TITLE
Fabric shell argument is not used

### ISSUE THREAD

**Issue by liny-nykline-com** [JasperVanDenBosch/fexpect#3]
Fabric has the "-s" argument to change the default shell, it seems  it's not used by fexpect.

Thanks!

**Comment by JasperVanDenBosch** [comment]
Thanks for reporting! This should be fixed in [0.2.post3](http://pypi.python.org/pypi/fexpect/0.2.post3), which is now on pypi. 

Note however that I am not sure as to which shell configuration will work, and the [normal fabric limitations](http://docs.fabfile.org/en/1.4.2/usage/env.html#shell) apply, and some things won't work for pexpect, but I have added a test for 'sh -c' which works.

Feel free to open a new issue if you encounter further trouble.

Jasper

**Comment by liny-nykline-com** [comment]
Oh great! I will try to test it right away!
